# DDD Taiwan 2025 Conference Website - Serena Project Configuration
# Next.js 15.5.2 + React 19 + TypeScript + Tailwind CSS

# Project language (TypeScript for Next.js project)
language: typescript

# Project identification
project_name: "DDD Taiwan 2025"

# File handling configuration
ignore_all_files_in_gitignore: true
ignored_paths:
  # Build and dependency directories
  - "node_modules/**"
  - ".next/**"
  - "out/**"
  - "build/**"
  - "dist/**"
  
  # Cache and temporary files
  - "*.tsbuildinfo"
  - ".pnpm-debug.log*"
  - "npm-debug.log*"
  - "yarn-debug.log*"
  - "yarn-error.log*"
  - "*.tmp"
  - "*.temp"
  
  # IDE and tool files
  - ".vscode/**"
  - ".idea/**"
  - "*.log"
  - ".DS_Store"
  - "Thumbs.db"
  
  # Generated files that are not business logic
  - "next-env.d.ts"
  - "pnpm-lock.yaml"
  - "package-lock.json"
  - "yarn.lock"
  
  # Environment and config that might contain secrets
  - ".env*"
  - ".vercel/**"
  
  # Large binary/media files for performance
  - "public/images/**/*.{jpg,jpeg,png,gif,svg,webp}"
  - "**/*.{mp4,avi,mov,wmv}"
  - "**/*.{pdf,zip,rar,7z}"

# Project access mode
read_only: false

# Tool configuration - exclude tools not needed for this project type
excluded_tools:
  # JetBrains specific tools (using VS Code instead)
  - "jet_brains_find_symbol"
  - "jet_brains_find_referencing_symbols" 
  - "jet_brains_get_symbols_overview"

# Initial context for the project
initial_prompt: |
  DDD Taiwan 2025 Conference 官網 - Next.js 15.5.2 + React 19 + TypeScript
  
  **核心規範:**
  - **t() 函式必須** - `const { t } = useI18n(); t('key.subkey')`
  - **config 導入** - 使用 `@/config`，避免硬編碼
  - **靜態 Tailwind** - 不使用字串插值
  - **stopPropagation()** - 處理巢狀事件
  - **kebab-case** - 檔案命名 (promo-code-copy.tsx)
  
  **重要系統:**
  - 票券系統 TICKET_SALE_CONFIG (config/tickets.ts)
  - 多語言系統 i18n Context
  - GitHub Pages 靜態部署
  - WebP 圖片優化
  
  **開發原則:**
  配置驅動開發，功能開關透過 config/ 控制
